### ISSUE TITLE
the server keeps connecting to clients even though the 'websocket' value in lib/config/app is false

### ISSUE THREAD

**Issue by WissamALSbenaty** [vania-dart/framework#78]
alternatively, it should be assigned to env('APP_WEBSOCKET')

I struggled to find out why the server always  receives the message and sends  "connect " message to the client without any effect and after a while 
I discovered that APP_WEBSOCKET in env file is set to false by default

**Comment by javad-zobeidi** [comment]
Please update to the last version of Vania

Websocket and some configs for better experience moved to the env file, and are no longer used since Vania 2.x

Use these files

The latest config file [config/app.dart](https://raw.githubusercontent.com/vania-dart/sample/main/lib/config/app.dart)

Latest env file [.env](https://raw.githubusercontent.com/vania-dart/sample/main/.env)

**Comment by WissamALSbenaty** [comment]
i am using Vania 2.7 
and created my project using the cli

maybe the starter project hasn't been updated? 
@javad-zobeidi
